routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>['maintenance'], 'as'=>'front.'], function() {

    Route::get('/', 'FrontController@index')->name('index');
    Route::get('/salon', 'FrontController@salon')->name('salon');
    Route::get('/category/{category}', 'FrontController@category')->name('category');
    Route::get('/category/{category}/product/{product}', 'FrontController@product')->name('product');
    Route::get('/filter', 'FrontController@filter')->name('filter');
    Route::post('/addToCart', 'FrontController@addToCart')->name('addToCart');
    Route::get('/order', 'FrontController@order')->name('order');
    Route::post('/remittance', 'FrontController@remittance')->name('remittance');
    Route::get('/teach', 'FrontController@teach')->name('teach');
    Route::get('/cart', 'FrontController@cart')->name('cart');
    Route::post('/removeToCart','FrontController@removeToCart')->name('removeToCart');
    Route::get('/updateCart','FrontController@updateCart')->name('updateCart');
    Route::get('/note', 'FrontController@note')->name('note');
    Route::post('/validateCheckout', 'FrontController@validateCheckout')->name('validateCheckout');
    Route::get('/cart2', 'FrontController@cart2')->name('cart2');
    Route::post('/validateOrderer', 'FrontController@validateOrderer')->name('validateOrderer');
    Route::any('/complete', 'FrontController@complete')->name('complete');

});

Route::group(['prefix'=>'laravel-filemanager','middleware'=> ['web','auth']],function(){
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
// 後台
// prefix URL為/webmin/?
// namespace Controllers 預設路徑為 "App\Http\Controllers\backend"
Route::group(['prefix'=>'webmin','namespace'=>'backend'], function() {
    // 登入登出
    Route::get('/','LoginController@index')->name('backend');
    Route::post('/','LoginController@session_in')->name('login');
    Route::get('/logout','LoginController@logout')->name('logout');

    // 登入後迎賓頁
    Route::group(['middleware'=>'auth:web'], function(){
        Route::get('/index','ModuleController@index')->name('backend.index');

        // 首頁管理
        Route::group(['prefix'=>'content', 'namespace'=>'content'], function() {
            // 首頁輪播
            Route::get('/home_banner', 'HomeBannerController@index')->name('backend.home_banner');
            Route::post('/home_banner', 'HomeBannerController@create')->name('create_home_banner');
            Route::post('/update_home_banner', 'HomeBannerController@update')->name('update_home_banner');
            Route::post('/delete_home_banner', 'HomeBannerController@delete')->name('delete_home_banner');


            // 產品及型錄管理
            // 分類管理ProductType
            Route::group(['middleware'=>'HasPermission:產品管理'], function() {
                // 分類管理
                Route::get('/productCategory', 'ProductCategoryController@index')->name('backend.productCategory');
                Route::post('/productCategory', 'ProductCategoryController@create')->name('create_productCategory');
                Route::post('/update_productCategory', 'ProductCategoryController@update')->name('update_productCategory');
                Route::post('/delete_productCategory', 'ProductCategoryController@delete')->name('delete_productCategory');


                // 產品管理
                Route::get('/productCategory/{category}/product', 'ProductController@index')->name('backend.product');
                Route::post('/product', 'ProductController@create')->name('create_product');
                Route::post('/update_product', 'ProductController@update')->name('update_product');
                Route::post('/delete_product', 'ProductController@delete')->name('delete_product');
                Route::get('/productCategory/{category}/product/{product}', 'ProductController@edit')->name('edit_product');
                Route::post('/update_filter', 'ProductController@update_filter')->name('update_filter');
                Route::get('/productCategory/{category}/product/{product}/photo', 'ProductController@photo')->name('category.edit_photo');
                Route::post('/photo', 'ProductController@create_photo')->name('create_photo');
                Route::post('/update_photo', 'ProductController@update_photo')->name('update_photo');
                Route::post('/delete_photo','ProductController@delete_photo')->name('delete_photo');
                Route::get('/productCategory/{category}/eyelash/{product}', 'ProductController@eyelash')->name('eyelash');
                Route::post('/option', 'ProductController@create_option')->name('create_option');
                Route::post('/delete_option', 'ProductController@delete_option')->name('delete_option');
                Route::post('/update_option', 'ProductController@update_option')->name('update_option');
                Route::get('/product/setting', 'ProductController@setting')->name('option.setting');
                Route::post('/update_setting', 'ProductController@update_setting')->name('update_setting');
                Route::get('/productList', 'ProductController@productList')->name('backend.productList');
                Route::get('/productList/{product}/photo', 'ProductController@listPhoto')->name('edit_photo');
                Route::get('/productList/{product}', 'ProductController@listEdit')->name('edit_productList');
                Route::get('/phone', 'ProductController@phone')->name('backend.phone');
                Route::post('/phone', 'ProductController@update_phoneOrder')->name('update_phoneOrder');


                // 睫毛規格管理
                Route::get('/eyelash', 'EyelashController@index')->name('backend.eyelash');
                Route::post('/eyelash', 'EyelashController@create')->name('create_type');
                Route::post('/delete_type', 'EyelashController@delete')->name('delete_type');
                Route::get('/eyelash/curl', 'EyelashController@curl')->name('backend.curl');
                Route::get('/eyelash/thickness', 'EyelashController@thickness')->name('backend.thickness');
                Route::get('/eyelash/length', 'EyelashController@length')->name('backend.length');
                Route::get('/eyelashList', 'EyelashController@eyelashList')->name('backend.eyelashList');
                Route::get('/eyelashList/{product}', 'EyelashController@detail')->name('eyelashList.detail');
            });


            // 圖片管理 - 教學
            Route::get('/teach', 'TeachController@index')->name('backend.teach');
            Route::post('/teach', 'TeachController@update')->name('update_teach');


            // 圖片管理 - 活動訊息
            Route::get('/news', 'NewsController@index')->name('backend.news');
            Route::post('/news', 'NewsController@update')->name('update_news');


            // 圖片管理 - 頁尾
            Route::get('/footer', 'FooterController@index')->name('backend.footer');
            Route::post('/footer', 'FooterController@update')->name('update_footer');

        });


        // 購物管理
        Route::group(['prefix'=>'shopping'], function() {
            Route::get('/setting', 'ShoppingController@index')->name('shopping.free');
            Route::post('/update_free', 'ShoppingController@update')->name('update_free');
            Route::get('/shipping', 'ShoppingController@shipping')->name('shopping.shipping');
            Route::post('/update_shipping', 'ShoppingController@update_shipping')->name('update_shipping');
            Route::get('/receipt', 'ShoppingController@receipt')->name('shopping.receipt');
            Route::post('/update_receipt', 'ShoppingController@update_receipt')->name('update_receipt');
            Route::get('/expired', 'ShoppingController@expired')->name('shopping.expired');
            Route::post('/expired', 'ShoppingController@update_expired')->name('update_expired');
            Route::get('/note', 'ShoppingController@note')->name('shopping.note');
            Route::post('/note', 'ShoppingController@update_note')->name('update_note');
            Route::get('/complete', 'ShoppingController@complete')->name('shopping.complete');
            Route::post('/complete', 'ShoppingController@update_complete')->name('update_complete');
        });


        // 訂單管理
        Route::group(['prefix'=>'order'], function() {
            Route::get('/', 'OrderController@index')->name('backend.order');
            Route::get('/arrearage', 'OrderController@arrearage')->name('backend.arrearage');
            Route::get('/shipment', 'OrderController@shipment')->name('backend.shipment');
            Route::get('/completed', 'OrderController@completed')->name('backend.completed');
            Route::get('/overdue', 'OrderController@overdue')->name('backend.overdue');
            Route::get('/cancel', 'OrderController@cancel')->name('backend.cancel');
            Route::get('/detail/{order}', 'OrderController@edit')->name('edit_order');
            Route::post('/', 'OrderController@update')->name('update_order');
            Route::get('/{id}/remittance', 'OrderController@remittance')->name('backend.remittance');
            Route::post('/update_remittance', 'OrderController@update_remittance')->name('update_remittance');
            Route::get('/export_shipment/{order}', 'OrderController@export_shipment')->name('export_shipment');
        });


        // 權限管理
        Route::group(['prefix'=>'authority'], function() {
            Route::get('/profile', 'AuthorityController@index')->name('profile');
            Route::post('/profile', 'AuthorityController@update')->name('update_profile');

app/Cart.php
<?php

    namespace App;

    class Cart
    {
        public $items = null;

        public function __construct($oldCart)
        {
            if($oldCart)
            {
                $this->items = $oldCart->items;
            }
        }

        public function add($item, $id, $quantity)
        {
            $storedItem = ['item' => $item, 'quantity' => (int)$quantity];
            if ($this->items) {
                if (array_key_exists($id, $this->items)) {
                    $this->items[$id]['quantity'] += $quantity;
                    $storedItem = $this->items[$id];
                }
            }

            $this->items[$id] = $storedItem;
        }

        public function remove($id)
        {
            // remove the item
            unset($this->items[$id]);
        }

        public function update($id, $quantity)
        {
            $this->items[$id]['quantity'] = $quantity;
        }

    }

resources/views/front/cart/complete.blade.php
@extends('front.cart.default')
    @section('content')
        <div class="cart-step">
            <img src="/images/cart_03.png" alt="">
        </div>
        <div class="orderNum-block">
            <h3>訂購完成！感謝您訂購JRO美睫商材。</h3>
            <h3>您的訂單編號為<span>{{ $order->number }}</span></h3>
        </div>
        <div>
            <!-- ↓圖文編輯器↓ -->
            {!! $complete->html !!}
            <!-- ↑圖文編輯器↑ -->
        </div>
    @endsection

resources/views/front/cart/default.blade.php
@extends('front.layouts.default')
    @section('header')
        @include('front.layouts.header')
    @endsection
    @section('footer')
        @include('front.layouts.footer')
    @endsection

resources/views/front/cart/note.blade.php
@extends('front.cart.default')
    @section('content')
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-6 col-lg-4">
                <div class="order-title">
                    <img class="left" src="/images/flower_left.png" alt="">
                    購物須知
                    <img class="right" src="/images/flower_right.png" alt="">
                </div>
            </div>
        </div>
        <div>
            <!-- ↓圖文編輯器↓ -->
            {!! $note->html !!}
            <!-- ↑圖文編輯器↑ -->
        </div>
        <div class="tc pt-3 pb-3">
            <a class="brownBTN" href="{{ route('front.cart') }}" title="">
                返 回
            </a>
        </div>
    @endsection

resources/views/front/cart/step2.blade.php
@extends('front.cart.default')
    @section('content')
        <div class="cart-step">
            <img src="/images/cart_02.png" alt="">
        </div>
        <div class="row justify-content-center">
            <div class="col-12 col-lg-11">
                <form id="orderer">
                    <div class="info-title">
                        購買人資訊
                    </div>
                    <table class="table table-borderless table-sm info-table mb-5">
                        <tbody>
                            <tr>
                                <td class="info-td-1">姓名：</td>
                                <td>
                                    <input type="text" class="form-control" name="buyer" value="{{ old('buyer') }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="info-td-1">電話：</td>
                                <td>
                                    <input type="text" class="form-control" name="buyer_tel" value="{{ old('buyer_tel') }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="info-td-1">地址：</td>
                                <td>
                                    <input type="text" class="form-control" name="buyer_addr" value="{{ old('buyer_addr') }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="info-td-1">Email：</td>
                                <td>
                                    <input type="text" class="form-control" name="email" value="{{ old('email') }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="info-td-1">需求備註：</td>
                                <td>
                                    <textarea class="form-control" name="demand" rows="3">{{ old('demand') }}</textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="info-title">
                        收貨人資訊
                    </div>
                    <table class="table table-borderless table-sm info-table mb-5">
                        <tbody>
                            <tr>
                                <td colspan="2">
                                    <label>
                                        <input type="checkbox" name="same"> 同購買人
                                    </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="info-td-1">姓名：</td>
                                <td>
                                    <input type="text" class="form-control" name="consignee" value="{{ old('consignee') }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="info-td-1">電話：</td>
                                <td>
                                    <input type="text" class="form-control" name="consignee_tel" value="{{ old('consignee_tel') }}">
                                </td>
                            </tr>
                            <tr>
                                <td class="info-td-1">地址：</td>
                                <td>
                                    <input type="text" class="form-control" name="consignee_addr" value="{{ old('consignee_addr') }}">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    @if($system->receipt)
                        <input type="hidden" name="receipt">
                        <div class="info-title">
                            發票資訊
                        </div>
                        <table class="table table-borderless table-sm info-table mb-5">
                            <tbody>
                                @foreach($receiptTypes as $receiptType)
                                    <tr>
                                        <td colspan="2">
                                            <label><input type="radio" name="receipt" value="{{ $receiptType->id }}"> {{ $receiptType->title }}{{ $receiptType->id == 4 ? '(捐贈單位： '.$receipt->title.' )' : '' }}</label>
                                        </td>
                                    </tr>
                                    @if($receiptType->id == 3)
                                        <tr style="display: none">
                                            <td class="info-td-1">抬頭：</td>
                                            <td>
                                                <input type="text" class="form-control" name="title" disabled>
                                            </td>
                                        </tr>
                                        <tr style="display: none">
                                            <td class="info-td-1">統編：</td>
                                            <td>
                                                <input type="text" class="form-control" name="VAT" disabled>
                                            </td>
                                        </tr>
                                    @elseif($receiptType->id  == 4)
                                        <input type="hidden" name="contribute" value="{{ $receipt->title }}" disabled>
                                    @endif
                                @endforeach
                            </tbody>
                        </table>
                    @endif
                    <div class="info-title">
                        請輸入驗證碼
                    </div>
                    <div>
                        {!! NoCaptcha::display() !!}
                    </div>

                    <div class="tr">
                        <a class="brownBTN2" href="{{ route('front.cart') }}" title="">
                            返 回
                        </a>
                        <input type="button" class="brownBTN2" value="完 成" onclick="store()">
                    </div>
                    @include('errors.error')
                    @include('errors.alertError')
                </form>
            </div>
        </div>

        <form id="complete" action="{{ route('front.complete') }}" method="post">
            @csrf
            <input type="hidden" name="id">
        </form>
    @endsection

    @section('js')
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
        <script>
            $('input[type="checkbox"]').on('click', _paste)
            $('input[name^="buyer"]').on('keyup', _paste)

            function _paste() {
                let _consignee = $('input[name="consignee"]');
                let _consignee_tel = $('input[name="consignee_tel"]');
                let _consignee_addr = $('input[name="consignee_addr"]');
                if ($('input[type="checkbox"]').prop('checked')) {
                    _consignee.val($('input[name="buyer"]').val());
                    _consignee_tel.val($('input[name="buyer_tel"]').val());
                    _consignee_addr.val($('input[name="buyer_addr"]').val());
                }
            }

            $('input[name="receipt"]').on('click', function () {
                if ($(this).val() == 3) {
                    $(this).closest('tbody').find(':nth-child(4), :nth-child(5)').css('display', '').find('input').attr('disabled', false);
                    $('input[name="contribute"]').attr('disabled', true);
                } else {
                    $(this).closest('tbody').find(':nth-child(4), :nth-child(5)').css('display', 'none').find('input').attr('disabled', true);
                    if($(this).val() == 4) {
                        $('input[name="contribute"]').attr('disabled', false);
                    } else {
                        $('input[name="contribute"]').attr('disabled', true);
                    }
                }
            })

            function store()
            {
                $('input[type="button"]').attr('disabled', true);
                $.ajax({
                    type : 'POST',
                    url: '{{ route('front.validateOrderer') }}',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    data: $('#orderer').serialize(),
                    error: function(data) {
                        var data = data.responseJSON;
                        errorsHtml = '<ul>';
                        $.each(data.errors, function(key,value){
                            errorsHtml += '<li>'+ value +'</li>';
                        });
                        errorsHtml += '</ul>';
                        Swal.fire({
                            title: '錯誤',
                            html: errorsHtml,
                            icon: 'warning',
                            showCloseButton: true,
                            showCancelButton: true,
                            showConfirmButton: false,
                        }).then(function (result) {
                            if (data.id) {
                                $('#complete input[name="id"]').val(data.id);
                                $('#complete').submit();
                            }
                        })
                        grecaptcha.reset();
                        $('input[type="button"]').attr('disabled', false);
                    },
                    success: function(data) {
                        $('#complete input[name="id"]').val(data);
                        $('#complete').submit();
                    }
                });
            }
        </script>
    @endsection